site_name: TA-crowdstrike-identities
edit_uri: edit/main/docs/
repo_url: https://github.com/ZachChristensen28/TA-crowdstrike-identities
repo_name: ZachChristensen28/TA-crowdstrike-identities
site_description: >-
  Welcome to the Home of the CrowdStrike Falcon Identity Protection Add-on for Splunk documentation. This Splunk Add-on allows ingestion of the CrowdStrike identity data into Splunk enabling the data to be used with other Splunk Apps, such as Enterprise Security.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - no-zoom
      auto_caption: true
      caption_position: bottom
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: overrides
  #   logo:
  #   favicon:
  icon:
    repo: fontawesome/brands/github
  # logo: assets/ta-crowdstrike-logo-small.svg
  # favicon: assets/ta-crowdstrike-logo-small.svg
  features:
    # - announce.dismiss
    # - header.autohide
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zachthesplunker/
    - icon: fontawesome/brands/github
      link: https://github.com/ZachChristensen28
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@ZachTheSplunker

copyright: Copyright &copy; 2023 ZachTheSplunker

nav:
  - Home: index.md
  - Quick Start:
      - 1 - Create API Token: quickstart/api-token.md
      - 2 - Install: quickstart/install.md
      - 3 - Configure Input: quickstart/input.md
  - Reference:
      - Changelog:
          - Release Notes: reference/releases/index.md
          # - Release History: reference/releases/release-history.md
      - Third-party software:
          - Credits: reference/credits.md
  #     - All Configurations: reference/all-configurations.md
  # - Troubleshooting:
  #     - troubleshooting/index.md
