name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - "TA-crowdstrike-identites/**"

permissions:
  contents: write

jobs:
  call-packaging-workflow:
    uses: ZachTheSplunker/app-wfa/.github/workflows/release.yml@main
    with:
      package-name: TA-crowdstrike-identites